services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
      target: api-final
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: ./
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: Asia/Tokyo
    networks:
      - app-network

  db:
    build:
      context: .
      dockerfile: docker/mysql.Dockerfile
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ito_denwa
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-ppassword",
        ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    name: app-network

# 名前付きボリュームの定義
volumes:
  mysql-data:
    name: mysql-data
